namespace CQ.Repository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class updatekeytype : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.Bus_Articles");
            DropPrimaryKey("dbo.Bus_Images");
            DropPrimaryKey("dbo.Bus_Products");
            DropPrimaryKey("dbo.Sys_Area");
            DropPrimaryKey("dbo.Sys_ItemsDetail");
            DropPrimaryKey("dbo.Sys_Items");
            DropPrimaryKey("dbo.Sys_ModuleButton");
            DropPrimaryKey("dbo.Sys_Module");
            DropPrimaryKey("dbo.Sys_Organize");
            DropPrimaryKey("dbo.Sys_RoleAuthorize");
            DropPrimaryKey("dbo.Sys_Role");
            DropPrimaryKey("dbo.Sys_UserLogOn");
            DropPrimaryKey("dbo.Sys_User");
            DropPrimaryKey("dbo.Sys_DbBackup");
            DropPrimaryKey("dbo.Sys_FilterIP");
            DropPrimaryKey("dbo.Sys_Log");
            AlterColumn("dbo.Bus_Articles", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Bus_Articles", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Bus_Articles", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Bus_Articles", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Bus_Images", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Bus_Images", "F_FId", c => c.Int(nullable: false));
            AlterColumn("dbo.Bus_Images", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Bus_Products", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Bus_Products", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Bus_Products", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Bus_Products", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_Area", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Area", "F_ParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_Area", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_Area", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_Area", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_ItemsDetail", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_ItemsDetail", "F_ItemId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_ItemsDetail", "F_ParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_ItemsDetail", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_ItemsDetail", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_ItemsDetail", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_Items", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Items", "F_ParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_Items", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_Items", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_Items", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_ModuleButton", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_ModuleButton", "F_ModuleId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_ModuleButton", "F_ParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_ModuleButton", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_ModuleButton", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_ModuleButton", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_Module", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Module", "F_ParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_Module", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_Module", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_Module", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_Organize", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Organize", "F_ParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_Organize", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_Organize", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_Organize", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_RoleAuthorize", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_RoleAuthorize", "F_ItemId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_RoleAuthorize", "F_ObjectId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_RoleAuthorize", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_Role", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Role", "F_OrganizeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_Role", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_Role", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_Role", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_UserLogOn", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_UserLogOn", "F_UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_User", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_User", "F_RoleId", c => c.Int(nullable: false));
            AlterColumn("dbo.Sys_User", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_User", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_User", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_DbBackup", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_DbBackup", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_DbBackup", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_DbBackup", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_FilterIP", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_FilterIP", "F_CreatorUserId", c => c.Int());
            AlterColumn("dbo.Sys_FilterIP", "F_LastModifyUserId", c => c.Int());
            AlterColumn("dbo.Sys_FilterIP", "F_DeleteUserId", c => c.Int());
            AlterColumn("dbo.Sys_Log", "F_Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Log", "F_CreatorUserId", c => c.Int());
            AddPrimaryKey("dbo.Bus_Articles", "F_Id");
            AddPrimaryKey("dbo.Bus_Images", "F_Id");
            AddPrimaryKey("dbo.Bus_Products", "F_Id");
            AddPrimaryKey("dbo.Sys_Area", "F_Id");
            AddPrimaryKey("dbo.Sys_ItemsDetail", "F_Id");
            AddPrimaryKey("dbo.Sys_Items", "F_Id");
            AddPrimaryKey("dbo.Sys_ModuleButton", "F_Id");
            AddPrimaryKey("dbo.Sys_Module", "F_Id");
            AddPrimaryKey("dbo.Sys_Organize", "F_Id");
            AddPrimaryKey("dbo.Sys_RoleAuthorize", "F_Id");
            AddPrimaryKey("dbo.Sys_Role", "F_Id");
            AddPrimaryKey("dbo.Sys_UserLogOn", "F_Id");
            AddPrimaryKey("dbo.Sys_User", "F_Id");
            AddPrimaryKey("dbo.Sys_DbBackup", "F_Id");
            AddPrimaryKey("dbo.Sys_FilterIP", "F_Id");
            AddPrimaryKey("dbo.Sys_Log", "F_Id");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.Sys_Log");
            DropPrimaryKey("dbo.Sys_FilterIP");
            DropPrimaryKey("dbo.Sys_DbBackup");
            DropPrimaryKey("dbo.Sys_User");
            DropPrimaryKey("dbo.Sys_UserLogOn");
            DropPrimaryKey("dbo.Sys_Role");
            DropPrimaryKey("dbo.Sys_RoleAuthorize");
            DropPrimaryKey("dbo.Sys_Organize");
            DropPrimaryKey("dbo.Sys_Module");
            DropPrimaryKey("dbo.Sys_ModuleButton");
            DropPrimaryKey("dbo.Sys_Items");
            DropPrimaryKey("dbo.Sys_ItemsDetail");
            DropPrimaryKey("dbo.Sys_Area");
            DropPrimaryKey("dbo.Bus_Products");
            DropPrimaryKey("dbo.Bus_Images");
            DropPrimaryKey("dbo.Bus_Articles");
            AlterColumn("dbo.Sys_Log", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_Log", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_FilterIP", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_FilterIP", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_FilterIP", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_FilterIP", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_DbBackup", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_DbBackup", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_DbBackup", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_DbBackup", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_User", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_User", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_User", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_User", "F_RoleId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_User", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_UserLogOn", "F_UserId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_UserLogOn", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Role", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_Role", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_Role", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_Role", "F_OrganizeId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_Role", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_RoleAuthorize", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_RoleAuthorize", "F_ObjectId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_RoleAuthorize", "F_ItemId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_RoleAuthorize", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Organize", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_Organize", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_Organize", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_Organize", "F_ParentId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_Organize", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Module", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_Module", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_Module", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_Module", "F_ParentId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_Module", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_ModuleButton", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_ModuleButton", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_ModuleButton", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_ModuleButton", "F_ParentId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_ModuleButton", "F_ModuleId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_ModuleButton", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Items", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_Items", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_Items", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_Items", "F_ParentId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_Items", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_ItemsDetail", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_ItemsDetail", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_ItemsDetail", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_ItemsDetail", "F_ParentId", c => c.String());
            AlterColumn("dbo.Sys_ItemsDetail", "F_ItemId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_ItemsDetail", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Sys_Area", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Sys_Area", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Sys_Area", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Sys_Area", "F_ParentId", c => c.Long(nullable: false));
            AlterColumn("dbo.Sys_Area", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Bus_Products", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Bus_Products", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Bus_Products", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Bus_Products", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Bus_Images", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Bus_Images", "F_FId", c => c.Long(nullable: false));
            AlterColumn("dbo.Bus_Images", "F_Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Bus_Articles", "F_DeleteUserId", c => c.Long());
            AlterColumn("dbo.Bus_Articles", "F_LastModifyUserId", c => c.Long());
            AlterColumn("dbo.Bus_Articles", "F_CreatorUserId", c => c.Long());
            AlterColumn("dbo.Bus_Articles", "F_Id", c => c.Long(nullable: false, identity: true));
            AddPrimaryKey("dbo.Sys_Log", "F_Id");
            AddPrimaryKey("dbo.Sys_FilterIP", "F_Id");
            AddPrimaryKey("dbo.Sys_DbBackup", "F_Id");
            AddPrimaryKey("dbo.Sys_User", "F_Id");
            AddPrimaryKey("dbo.Sys_UserLogOn", "F_Id");
            AddPrimaryKey("dbo.Sys_Role", "F_Id");
            AddPrimaryKey("dbo.Sys_RoleAuthorize", "F_Id");
            AddPrimaryKey("dbo.Sys_Organize", "F_Id");
            AddPrimaryKey("dbo.Sys_Module", "F_Id");
            AddPrimaryKey("dbo.Sys_ModuleButton", "F_Id");
            AddPrimaryKey("dbo.Sys_Items", "F_Id");
            AddPrimaryKey("dbo.Sys_ItemsDetail", "F_Id");
            AddPrimaryKey("dbo.Sys_Area", "F_Id");
            AddPrimaryKey("dbo.Bus_Products", "F_Id");
            AddPrimaryKey("dbo.Bus_Images", "F_Id");
            AddPrimaryKey("dbo.Bus_Articles", "F_Id");
        }
    }
}
